Created feature add city weather
trademasterbr/tm-challenge-code-review pull request #2
Opened 2024-01-03 19:24 UTC by andersonbtt

2024-01-12 11:07 UTC, StringherTest commented on README.md
> +
Remover imagem do arquivo readme.

2024-01-12 11:12 UTC, StringherTest commented on README.md
Inserir descritivo das funcionalidades da API, conforme abaixo:
O Weather Forecast API é um hub que reunirá diversas informações sobre clima e será consumido por empresas do agronegócio, aviação, militar, turismo, etc. Seu principal objetivo é consumir diversos serviços de terceiros e fornecer dados concisos.

Principais recursos:

-Buscar temperaturas pelo nome da cidade
-Buscar temperaturas em lote, enviando uma lista de cidades
- Retornar a temperatura média de uma cidade

2024-01-12 11:22 UTC, StringherTest commented on src/main.ts
> +}
Ajustar  com a inserção do bloco Try Catch para possiveis erros de inicialização

async function bootstrap() {
  try {
    const app = await NestFactory.create(AppModule);

    // Configuração flexível para a porta
    const PORT = process.env.PORT || 3001;

    await app.listen(PORT);
    console.log(`Application is running on port ${PORT}`);
  } catch (error) {
    console.error('Error during application bootstrap:', error);
    process.exit(1); // Encerra o processo em caso de erro
  }
}

2024-01-12 11:26 UTC, StringherTest commented on src/weather/weather.controller.ts
> +  @Get('/city')
@Get('/cities/:city')  utilizar parametro de rota e não direto no Body

2024-01-12 11:27 UTC, StringherTest commented on src/weather/weather.controller.ts
> +
Pegar o parametro pela rota e não pelo Body
@Get('/city/:city')
  async getCity(@Param('city') city: string): Promise<any> {
    return await this.service.getCity(city);
  }

2024-01-12 11:34 UTC, StringherTest commented on src/weather/weather.controller.ts
> +  }
Remover @HttpCode(201) deve ser usado com POST e PUT

2024-01-12 11:50 UTC, StringherTest commented on src/weather/weather.service.ts
> +        }
A chave da API está exposta e compartilhada no GitHub, precisa criar um arquivo a parte com a credencial, e adicionar regra no gitignore para o arquivo com a chave.
Se for o caso armazenar em variavel de ambiente e fazer o alinhamento com o time de Devops para o Deploy

2024-01-12 11:56 UTC, StringherTest commented on src/weather/weather.service.ts
> +
forEach não aguarda operações assíncronas, refazer com o codigo abaixo usando for

 async getCities(cities: any): Promise<Array<WeatherResponseData>> {
    const resultArray: Array<WeatherResponseData> = [];

    for (const city of cities.array) {
      try {
        const rc = {
          headers: {
            'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
            'Content-Type': 'application/json'
          }
        };
        const { data } = await firstValueFrom(
          this.httpService.get<WeatherResponseData>(`https://api.api-ninjas.com/v1/weather?city=${city.city}`, rc).pipe(
            catchError((error: AxiosError) => {
              console.error(error.response?.data);
              throw error.response?.data || 'Erro desconhecido';
            })
          )
        );
        resultArray.push(data);
      } catch(err) {
        console.error(err);
        throw new InternalServerErrorException({
          descriptionOrOptions: err,
        });
      }
    }

    return resultArray;
  }

2024-01-12 11:58 UTC, StringherTest commented on src/weather/weather.service.ts
> +}
Metodo sem tratamento de erro, response é uma promessa e não está sendo aguardado. Usar await para aguardar o resultado da promessa antes de acessar propriedades

async getMedia(city: any): Promise<string> {
    try {
      const response = await this.getCity(city);
      return `${(response.max_temp + response.min_temp) / 2}`;
    } catch(err) {
      console.error(err);
      throw new InternalServerErrorException({
        descriptionOrOptions: err,
      });
    }

2024-01-12 12:25 UTC, StringherTest requested changes
Segue Code Review, só não entendi bem se o intuito do programa era consumir as apis do Api ninja ou se o programa deveria ter a base de dados estruturada com uma camada de model para consumo das informações

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.service.ts
> +          catchError((error: AxiosError) => {
Crie um módulo TypeScript dedicado para armazenar  URLs de API. Isso pode ser feito criando um arquivo como config.ts com constantes TypeScript.

export const WEATHER_API_URL = 'https://api.weather.com';
export const USER_API_URL = 'https://api.user.com';

// Exemplo de uso no código TypeScript
import { WEATHER_API_URL, USER_API_URL } from './config';

depois disso usar as constantes WEATHER_API_URL e USER_API_URL no seu código

2024-01-12 12:25 UTC, StringherTest commented on README.md
> +
Remover imagem do arquivo readme.

2024-01-12 12:25 UTC, StringherTest commented on README.md
Inserir descritivo das funcionalidades da API, conforme abaixo:
O Weather Forecast API é um hub que reunirá diversas informações sobre clima e será consumido por empresas do agronegócio, aviação, militar, turismo, etc. Seu principal objetivo é consumir diversos serviços de terceiros e fornecer dados concisos.

Principais recursos:

-Buscar temperaturas pelo nome da cidade
-Buscar temperaturas em lote, enviando uma lista de cidades
-Retornar a temperatura média de uma cidade

2024-01-12 12:25 UTC, StringherTest commented on src/main.ts
> +}
Ajustar com a inserção do bloco Try Catch para possiveis erros de inicialização

async function bootstrap() {
try {
const app = await NestFactory.create(AppModule);

// Configuração flexível para a porta
const PORT = process.env.PORT || 3001;

await app.listen(PORT);
console.log(`Application is running on port ${PORT}`);
} catch (error) {
console.error('Error during application bootstrap:', error);
process.exit(1); // Encerra o processo em caso de erro
}
}

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.controller.ts
> +
Remover @httpcode(201) deve ser usado com POST e PUT
Mudar o nome do metodo CreateAccessToken, está confuso, o metodo retorna dados de tempo

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.controller.ts
> +  @HttpCode(201)
Remover @httpcode(201) deve ser usado com POST e PUT

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.controller.ts
> +  @HttpCode(201)
Remover @httpcode(201) deve ser usado com POST e PUT

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.service.ts
> +          'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
A chave da API está exposta e compartilhada no GitHub, precisa criar um arquivo a parte com a credencial, e adicionar regra no gitignore para o arquivo com a chave.
Se for o caso armazenar em variavel de ambiente e fazer o alinhamento com o time de Devops para o Deploy

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.service.ts
> +
forEach não aguarda operações assíncronas, refazer com o codigo abaixo usando for

async getCities(cities: any): Promise<Array> {
const resultArray: Array = [];

for (const city of cities.array) {
  try {
    const rc = {
      headers: {
        'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
        'Content-Type': 'application/json'
      }
    };
    const { data } = await firstValueFrom(
      this.httpService.get<WeatherResponseData>(`https://api.api-ninjas.com/v1/weather?city=${city.city}`, rc).pipe(
        catchError((error: AxiosError) => {
          console.error(error.response?.data);
          throw error.response?.data || 'Erro desconhecido';
        })
      )
    );
    resultArray.push(data);
  } catch(err) {
    console.error(err);
    throw new InternalServerErrorException({
      descriptionOrOptions: err,
    });
  }
}

return resultArray;
}

2024-01-12 12:25 UTC, StringherTest commented on src/weather/weather.service.ts
> +}
Metodo sem tratamento de erro, response é uma promessa e não está sendo aguardado. Usar await para aguardar o resultado da promessa antes de acessar propriedades

async getMedia(city: any): Promise {
try {
const response = await this.getCity(city);
return ${(response.max_temp + response.min_temp) / 2};
} catch(err) {
console.error(err);
throw new InternalServerErrorException({
descriptionOrOptions: err,
});
}

2024-01-12 12:25 UTC, StringherTest commented on README.md
Use o seguinte comando para construir o projeto:
yarn build
# ou
npm run build

2024-01-15 19:02 UTC, lcs1015 commented on yarn.lock
No Readme ele pede para usar npm install poreḿ o lock do projeto está com yarn, definir um gerenciador de pacotes, aconselho o pnpm pois o build dele é consideravelmente mais rápido que os demais.
https://pnpm.io/pt/

2024-01-15 19:03 UTC, lcs1015 commented on src/app.controller.ts
Remover arquivos criados automaticamente pela CLI do Nest (app.controller, app.service e app.controller.spec)  se atentar para remover do app.module.

2024-01-15 19:03 UTC, lcs1015 commented on src/app.service.ts
Remover arquivos criados automaticamente pela CLI do Nest (app.controller, app.service e app.controller.spec)  se atentar para remover do app.module.

2024-01-15 19:06 UTC, lcs1015 commented on src/weather/weather.controller.ts
No geral muitos erros de indentação e importações não sendo utilizadas, não foi utilizado nenhum linting como ESLINT para garantir a boa indentação e manutenção do código, ajudando na melhoria de boas práticas no código em geral.

2024-01-15 19:10 UTC, lcs1015 commented on src/weather/weather.controller.ts
> +import { WeatherResponseData } from "./weather.response.data";
Esse é uma interface de resposta da api, ela está declarada e não está sendo usada, mais abaixo tem os lugares onde ela deveria estar, seria legal criar ela como um DTO, usar o padrão DTO (Data Transfer Object) para melhorar a transferência de dados entre camadas podendo ser estendido e usado futuramente economizando tempo e tornando o codigo mais reutilizavel, nome do arquivo ficaria weather.response.dto.ts

2024-01-15 19:30 UTC, lcs1015 commented on src/weather/weather.controller.ts
> +  }
Por se tratar de um GET o HttpCode deveria ser um 200, e ao invés de o decorator @Body utilizar o @Query() que segue os padrões para requisições do verbo GET.

O nome da função não contempla o que ela faz, poderia ser usado um findCity ou um getCity para seguir o padrão da service.

Aqui a Promisse com o tipo Any, não sendo uma boa pratica também, deveriamos usar o WeatherResponseData que comentei acima que está declarado e não sendo utilizado, que seria nosso DTO.
 Promise<WeatherResponseData>

2024-01-15 19:37 UTC, lcs1015 commented on src/weather/weather.controller.ts
> +  @HttpCode(201)
Mesmos detalhes da controller acima, em relação ao decorator, colocar status code 200 e Retorno da Promise está como any, nesse caso por se tratar de um array ela deveria estar tipada com Promise<WeatherResponseData[]>

2024-01-15 19:49 UTC, lcs1015 commented on src/weather/weather.response.data.ts
Essa classe poderia ser um DTO como comentado acima, e estar dentro de uma pasta /dtos pois podemos ter variod DTO para uma mesma controller, isso é uma otima pratica.

2024-01-15 19:56 UTC, lcs1015 commented on src/weather/weather.service.ts
No geral na service vejo muito o uso do try catch o que não é um problema, mas podemos criar uma exception filter como no exmplo abaixo removendo as nescessidade de tantos try catch utiizando só em momentos especificos quando precisarmos lidar com o erro retornado de alguma forma, não esqueça de registar esse filtro no app.module

// custom-exception.filter.ts
import { ExceptionFilter, Catch, ArgumentsHost, HttpException, HttpStatus } from '@nestjs/common';
import { Response } from 'express';

@Catch()
export class CustomExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const status = exception instanceof HttpException ? exception.getStatus() : HttpStatus.INTERNAL_SERVER_ERROR;

    response.status(status).json({
      statusCode: status,
      message: exception.message || 'Internal Server Error',
    });
  }
}

2024-01-15 20:00 UTC, lcs1015 commented on src/weather/weather.service.ts
> +          'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
Uma boa pratica é colcoar dados sensiveis/mutaveis na variavel de ambiente do projeto, para não ocorrer a exposição desses dados, que é uma falha de segurança grave.
E essa variavel de ambiente não ser exposta nos commits, fazemos isso adicionando ela no gitignore.

2024-01-15 20:07 UTC, lcs1015 commented on src/weather/weather.service.ts
> +        this.httpService.get<WeatherResponseData>(`https://api.api-ninjas.com/v1/weather?city=${city.city}`, rc).pipe(
Armanzene as urls de requisições também no arquivo de .ENV (WEATHER_API_URL = 'https://api.api-ninjas.com/v1' ) assim caso precisamos mudar a url de acordo com o ambiente de DEV, HML e PROD fica muito mais facíl através desse arquivo na nossa esteira.

Outro ponto, a variavel city já é a string que você precisa, não precisa acessar city.city

corrija para `${process.env.WEATHER_API_URL}/weather?city=${city}`

2024-01-15 20:24 UTC, lcs1015 commented on src/weather/weather.service.ts
> +            throw error.response.data;
Esse tipo de log é interessante ser guardado para futuramente poder ser apresentado ao user em tela ou mesmo para saber os motivos de uma integração falha, podemos armazenar no banco de dados por exemplo.

Outro ponto seria implementar retrys nas chamadas caso a api de terceiro fique ausente por poucos tempo conseguimos continuar com a solicitação do client ser causar desconforto.

Aqiu segue um exemplo de retry simples para implementar, discutir quanto tempo colocar de intervalo com o time mais tarde.
  async getCity(
    city: string,
    retryCount: number = 3,
  ): Promise<WeatherResponseDataDTO> {
    const rc = {
      headers: {
        'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
        'Content-Type': 'application/json',
      },
    };

    try {
      const { data } = await firstValueFrom(
        this.httpService
          .get<WeatherResponseDataDTO>(
            `https://api.api-ninjas.com/v1/weather?city=${city}`,
            rc,
          )
          .pipe(
            catchError(async (error) => {
              console.log(error.response.data);

              if (retryCount > 0) {
                console.log(`Retrying... (${retryCount} retries left)`);
                await new Promise((resolve) => setTimeout(resolve, 1000));
                return this.getCity(city, retryCount - 1);
              } else {
                throw error.response.data;
              }
            }),
          ),
      );

      return data;
    } catch (err) {
      throw new InternalServerErrorException({
        descriptionOrOptions: err,
      });
    }
  }

2024-01-15 20:42 UTC, lcs1015 commented on src/weather/weather.service.ts
> +  }
Neste trecho além de colocar o retry também, podemos observar que o foreach não aguarda a conclusão das chamadas assíncronas, o que pode causar erros, podemos usar um map junto com promise.all ou um for .

O tratamento de erros deveria ser individualmente pois se uma chamada para uma cidade falhar o código lança uma exceção geral, seria legal tratar para cada cidade, a menos que a regra de negocio não permita.

O ideial seria mudar o nome do array x para cidades já que está fora de contexto, e inicializar o array para evitar erros de undefined.

O parametro recebido na funcão está tipado com any o que não é uma boa pratica, podemos criar um DTO para ele com citiesDTO 
export class CitiesDto {
  cities: string[];
}

Segue exemplo de uma função melhor
async getCities(cities: CitiesDto): Promise<Array<WeatherResponseDataDTO>> {
  const x: Array<WeatherResponseDataDTO> = [];

  try {
    const rc = {
      headers: {
        'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
        'Content-Type': 'application/json',
      },
    };

    await Promise.all(cities.map(async (city) => {
      try {
        const { data } = await firstValueFrom(
          this.httpService
            .get<WeatherResponseDataDTO>(
              `https://api.api-ninjas.com/v1/weather?city=${city.city}`,
              rc,
            )
            .pipe(
              catchError((error: AxiosError) => {
                console.log(`Error for city ${city.city}: ${error.response.data}`);
                throw error.response.data;
              }),
            ),
        );
        x.push(data);
      } catch (err) {
        // Trate o erro individualmente para cada cidade, se necessário
        console.error(`Error processing city ${city.city}: ${err}`);
      }
    }));

    return x;
  } catch (err) {
    throw new InternalServerErrorException({
      descriptionOrOptions: err,
    });
  }
}

2024-01-15 20:47 UTC, lcs1015 commented on src/weather/weather.service.ts
> +  async getMedia(city: any): Promise<string> {
Essa função não está sendo usada, porém tem os mesmo erros que a controller de getAverage, mudar na controller o para chamar essa função e ajustar os mesmo erros ditos na controller nessa função ou apagar essa função e usar no modo que está na controller, aconselho apagar na controller e chamar essa função, já que regra de negocio é uma boa pratica manter nos serviços caso precise ser reaproveitado.

2024-01-15 21:25 UTC, lcs1015 reviewed
Comentários feitos e revisões solicitadas.

2024-01-25 16:35 UTC, nascimentolh commented on README.md
>  # Weather Forecast API
Antes de começar o review acredito que deviamos seguir um padrão de arquitetura para facilitar a manutenção do codigo no futuro e colaboração dos demais membros do time.

Peço que altere a estrutura de pastas para seguinte: 
```
src/
|--weather/
    |-- domain/
        |-- interfaces/
            |-- weather.service.interface.ts
        |-- entities/
            |-- city.ts
        |-- services/
            |-- weather.service.ts
    |-- infrastructure/
        |-- http/
            |-- weather.http.service.ts
    |-- application/
        |-- controllers/
            |-- weather.controller.ts
    |-- weather.module.ts
```
Vamos seguir uma arquitetura Hexagonal.

2024-01-25 16:35 UTC, nascimentolh commented on README.md
Antes de começar o review acredito que deviamos seguir um padrão de arquitetura para facilitar a manutenção do codigo no futuro e colaboração dos demais membros do time.

Peço que altere a estrutura de pastas para seguinte: 
```
src/
|--weather/
    |-- domain/
        |-- interfaces/
            |-- weather.service.interface.ts
        |-- entities/
            |-- city.ts
        |-- services/
            |-- weather.service.ts
    |-- infrastructure/
        |-- http/
            |-- weather.http.service.ts
    |-- application/
        |-- controllers/
            |-- weather.controller.ts
    |-- weather.module.ts
```
Vamos seguir uma arquitetura Hexagonal.

2024-01-25 16:40 UTC, nascimentolh commented on src/weather/weather.service.ts
> +  async getCity(city: any): Promise<WeatherResponseData> {
O uso de **any** não é uma boa abordagem, pois não haverá uma checagem de tipo em tempo de compilação. Corrija o parâmetro city passando o tipo adequado para ele, ou criando uma interface. No caso em questão acredito que uma **"city: string"** seja o correto.

2024-01-25 16:46 UTC, nascimentolh commented on src/weather/weather.service.ts
> +          'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
Ao invés de deixar as chaves de API expostas no codigo, utilize dos modulos presente no Nest.JS para armazenar estas chaves em variávies de ambiente. Você pode utilizar o modulo Config do Nest.JS instalando o mesmo através do comando.
`npm i --save @nestjs/config` em caso de duvidas você pode, consultar alguem do time ou utilizar a [documentação](https://docs.nestjs.com/techniques/configuration) deste modulo.

2024-01-25 17:54 UTC, nascimentolh commented on src/weather/weather.service.ts
> +import { Injectable, InternalServerErrorException } from "@nestjs/common";
O arquivo em questão possui diversos erros, como o uso inadequado de tipagem de parâmetros, por exemplo, "city: any". Isso implica em não ocorrer a checagem de tipagem em tempo de compilação.

Além disso, ocorre a exposição de chaves de API, onde deveríamos armazenar essas chaves em variáveis de ambiente e utilizar o módulo de configuração do Nest.js para lidar com isso de forma global.

Seguindo a linha do meu outro comentário, a arquitetura do projeto precisa ser alterada, e o arquivo abaixo ficaria da seguinte forma:

É necessário criar uma interface de implementação `weather/domain/interfaces/weather.service.interface.ts`

```
import { WeatherResponse } from './weather.response.interface';

export interface IWeatherService {
  getCityWeather(cityName: string): Promise<WeatherResponse>;
  getCitiesWeather(citiesNames: string[]): Promise<WeatherResponse[]>;
}
```
Na interface acima, estamos corrigindo o erro de tipagem que estava sendo cometido ao utilizar "city: any" e "cities: any". Dessa forma, não correremos mais o risco de passar tipos que não são suportados pela API.

Para a próxima parte, é necessário ter instalado no projeto o módulo Configuration, que é nativo do NestJS. Isso resolverá o problema de exposição da chave de API diretamente no código. Para instalar, basta usar o comando: `npm i --save @nestjs/config`
Em caso de dúvidas, você pode consultar a documentação do Nest.js ou perguntar a alguém da equipe.

Vamos criar o arquivo : `weather/infrastructure/http/weather.http.service.ts`

```
... Importaçoes ...

@Injectable()
export class WeatherHttpService {
    private readonly logger = new Logger(WeatherHttpService.name);
    private apiKey: string;
    private apiURL: string;

  constructor(private httpService: HttpService, private configService: ConfigService) {
    this.apiKey = this.configService.get<string>('WEATHER_API_KEY');
    this.apiURL = this.configService.get<string>('WEATHER_API_URL');
  }

  async getCityWeather(cityName: string): Promise<WeatherResponseData> {
    const url = `${this.apiURL}?city=${encodeURIComponent(cityName)}`;
    const headers = { 'X-Api-Key': this.apiKey };
    try {
      this.logger.log(`Buscando previsão do tempo para a cidade: ${cityName}`);
      const response = await firstValueFrom(this.httpService.get<WeatherResponseData>(url, { headers }));
      return response.data;
    } catch (error) {
        this.logger.error(`Erro ao buscar previsão do tempo para a cidade: ${cityName}`, error.stack);
        if (error instanceof AxiosError) {
          throw new HttpException('Erro ao comunicar com a API externa', HttpStatus.BAD_GATEWAY);
        }
        throw new InternalServerErrorException('Erro interno no servidor');
    }
  }
}
```

E em seguida fazer as alterações no nosso arquivo em questão que é `weather/domain/services/weather.service.ts`

```
... Importaçoes ...

@Injectable()
export class WeatherService implements IWeatherService {
  constructor(private weatherHttpService: WeatherHttpService) {}

  async getCityWeather(cityName: string): Promise<WeatherResponseData> {
    return this.weatherHttpService.getCityWeather(cityName);
  }

  async getCitiesWeather(citiesNames: string[]): Promise<WeatherResponseData[]> {
    return Promise.all(citiesNames.map(cityName => this.getCityWeather(cityName)));
  }
}
```

2024-01-25 18:25 UTC, nascimentolh commented on src/weather/weather.controller.ts
> +import { Injectable, Controller, Inject, Post, HttpCode, Body, Get } from "@nestjs/common";
No nosso controller, devemos prestar atenção aos seguintes pontos:
Tipo de retorno fora do padrão correto: Não é comum utilizar o status 201 (Created) para requisições do tipo GET. O status mais apropriado para uma resposta bem-sucedida em uma solicitação GET é 200 (OK).
Uso de parâmetros no corpo da requisição quando estamos falando de um método GET: Os parâmetros em uma solicitação GET devem ser passados na URL como parâmetros de consulta (query parameters), em vez de no corpo da requisição. É uma prática recomendada seguir os padrões RESTful para a criação de APIs.
Tipagem incorreta no método getCities: Certifique-se de que a tipagem dos parâmetros e do retorno esteja correta, de acordo com o que a função realmente espera e retorna.
Vamos corrigir o nosso controller para que ele siga as práticas adequadas de uma API RESTful:

```
... Importações ...

@Controller('weather')
export class WeatherController {
    constructor(private weatherService: WeatherService) {}

    @Get(':city')
    async getWeather(@Query('city') city: string): Promise<WeatherResponseData> {
        return this.weatherService.getCityWeather(city);
    }

    @Get('cities')
    async getCitiesWeather(@Query('names') cityNames: string[]): Promise<WeatherResponseData[]> {
        return this.weatherService.getCitiesWeather(cityNames);
    }
  
    @Get('average')
    async getCityAverage(@Query('city') city: string): Promise<WeatherResponseData> {
        return this.weatherService.getCityAverage(city);
    }
}
```
No arquivo acima fizemos as alterações dos para QueryParams, e removemos os 201, alem de adicionar a tipagem correta nos parâmetros.
Alem de utilizar a função `getCityAverage` que é a antiga `getMedia` que era inutilizada dado que foi feito um codigo repetido, com o mesmo conteudo da função.

2024-01-25 18:26 UTC, nascimentolh commented on src/app.service.ts
Remover a classe que não é utilizada no projeto.

2024-01-25 18:26 UTC, nascimentolh commented on src/app.controller.ts
Remover a classe que não é utilizada no projeto.

2024-01-25 18:27 UTC, nascimentolh commented on src/app.controller.spec.ts
Remover a classe que não é utilizada no projeto.

2024-01-25 18:48 UTC, nascimentolh requested changes
Os comentários desse code-review foram adicionados em seus respectivos arquivos.

2024-01-30 15:06 UTC, closed without merging

2024-02-26 21:21 UTC, DiegoTeles commented
Além das solicitações pendentes como remoção de arquivos de inicialização do nest, podemos estruturar o projeto de uma foma mais organizada, já que o Nest trabalha com arquitetura Modular.

Sugestões de melhorias para escalabilidade e rastreamento de falhas:

- Criar DTO para colocar os types do projeto 
- Inclusão de bibliotecas para logging, como a Winston
- Inclusão de bibliotecas para docs, como a swagger
- Criação de um arquivo de váriaveis de ambiente para incluão de dados sensíveis e remover URL's e chaves do código
- Testes unitários para validar as funções da services como `getCities` e  `getCity` e outras validações que surgirem
- Estar atento aos status code para não colocar o status de `created (201)` em uma chamada de get que é `ok (200)`
- Criar um Readme mais intuitivo como citado no review
- Caso o projeto escale para uso de database, sugiro o uso do sequelize e dockerizar a aplicação

Sugestão de testes:

```javascript
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, HttpStatus } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';
import { WeatherService } from './../src/weather.service';

describe('WeatherService', () => {
  let app: INestApplication;
  let weatherService: WeatherService;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
      providers: [WeatherService],
    }).compile();

    app = moduleFixture.createNestApplication();
    weatherService = moduleFixture.get<WeatherService>(WeatherService);
    await app.init();
  });

  afterEach(async () => {
    await app.close();
  });

  it('should return weather data for a city', async () => {
    const city = { city: 'London' };
    const data = await weatherService.getCity(city);
    expect(data).toBeDefined(); 
  });

  it('should return weather data for multiple cities', async () => {
    const cities = [{ city: 'London' }, { city: 'Paris' }];
    const data = await weatherService.getCities(cities);
    expect(data).toHaveLength(2); 
  });
});
```

2024-02-26 21:24 UTC, DiegoTeles commented on src/main.ts
> +  await app.listen(3001);
Uma sugestão para rastreabilidade seria de incluir a biblioteca [winston](https://github.com/gremo/nest-winston#readme) para ter logs mais intuitivos

2024-08-13 15:48 UTC, gitrodrigues1 reviewed
Realizado review, com algumas sugestões a serem implementadas. 

É importante de frisar que, por se tratar de uma avaliação, estou dando ênfase a alguns detalhes que no dia a dia normalmente não seriam especificados em um code review. Os erros abaixo poderiam ser solucionados em um pair programming ou habilitando o linter. Além disso os erros expostos estariam mitigados por uma esteira de CI/CD, que recusaria o commit, por haver certos erros no código.

2024-08-13 15:48 UTC, gitrodrigues1 commented on README.md
Muito já foi falado a respeito do readme e com bastante relevância, porém segue aqui a minha contribuição:

Visando as boas práticas de programação, é recomendado utilizar no projeto, conceitos como, clean arch, solid, ddd e design patterns. Sendo assim, deixarei algumas sugestões de melhoria e correções em alguns pontos. 

- Estrutura do projeto: Utilizar um modelo de pastas adequado para separar cada classe de acordo com sua responsabilidade, assim como sugere na arquitetura limpa.

- Especificar na documentação as dependências utilizadas no projeto e instruções de uso.

- Interfaces: Para que ocorra o desacoplamento, é necessário utilizar interfaces que irão conter funcionalidades da regra de negócio a serem implementadas pela aplicação. 

- Especificar os endpoints da API e incluir exemplos.

Obs: É importante de frisar que, por se tratar de uma avaliação, estou dando ênfase a detalhes que no dia a dia normalmente não seriam especificados em um code review. Os erros em código poderiam ser solucionados em um pair programming ou habilitando o linter. Além disso os erros expostos estariam mitigados por uma esteira de CI/CD, que recusaria o commit, por haver certos erros no código.

2024-08-13 15:48 UTC, gitrodrigues1 commented on src/app.controller.ts
- a anotação @Injectable não é necessária de ser incluída na classe, pois ela não será injetada em nenhum outro ponto da aplicação. 

- a anotação @Inject não é necessária neste ponto, pois a injeção da dependência já está sendo feita a nível do construtor. Portanto, torna-se redundante.


- a anotação @HttpCode(201) está retornando o código Http 201 (CREATED), não apropriado para requisições do tipo GET. O mais adequado neste ponto é retornar 200 (OK). Porém, não há necessidade de incluir a anotação neste ponto do código, pois o próprio framework Nestjs já retorna a requisição GET com o código 200.

- A fim de aproveitar melhor as funcionalidades do typescript, recomenda-se tipar o retorno das funções com uma classe específica e evitar retornar `Promise<any>`. Por exemplo, no método getCities, poderíamos retornar uma Promise com um objeto contendo o token.

- uso incorreto de async/await no método getAverage: Retirar o await da linha 28 e colocar antes da chamada da função na linha 27.
Não é recomendado exibir na camada de controller regras de negócio contendo expressões. A camada recomendada onde ficam as regras de negócio é a camada Service. Dependendo da arquitetura utilizada, a regra de negócio pode ficar também no domínio da camada core.

2024-08-13 15:48 UTC, gitrodrigues1 commented on src/app.service.ts
Esta classe possui situações de melhoria em diversos pontos:

- exposição de dados sensíveis: O código possui a api-key da api-ninjas. Para evitar a exposição dos dados, é necessário utilizar o arquivo .env contendo variáveis de ambiente e utilizar uma solução de armazenamento de secrets, como o GitHub secrets por exemplo. 

- erros de compilação: o código possui erros e não será possível de ser executado. 
no método getCity, possui a variável city.city que não existe. necessário substituir pelo argumento utilizado na arrow function.

- uso incorreto de async/await no método getMedia: Retirar o await da linha 67 e colocar antes da chamada da função na linha 66.

- Não está sendo utilizada a tipagem do typescript nos argumentos dos métodos. Todos eles estão usando o tipo any. A principal finalidade do typescript é auxiliar na tipagem dos objetos para evitar erros em tempo de compilação ou execução do projeto. 

- reuso de variáveis: temos headers em 2 métodos. Poderia ser colocado em uma variável e reutilizado quando necessário.

2024-09-05 04:36 UTC, andre5-augusto reviewed
O método createAccessToken não segue o padrão REST, pois usa o verbo GET para uma operação que espera receber dados no corpo da requisição.
Uso incorreto de @Body() com GET: O decorador @Body() não deveria ser usado em requisições GET, já que GET deve apenas receber parâmetros via query string ou params.
Métodos como getCity e getAverage têm lógica redundante, especialmente no cálculo da média de temperatura.
Status HTTP inadequado: O código de resposta 201 Created é utilizado em operações de leitura, mas o correto seria 200 OK.
Recomendações:
Uso de @Query() para parâmetros em requisições GET.
Refatoração de lógica duplicada: Extração da lógica de cálculo de média para o WeatherService.
Correção dos status HTTP para 200.

Corrigindo:

import { Controller, Get, Query, HttpCode } from "@nestjs/common";
import { WeatherService } from "./weather.service";

@Controller('weather')
export class WeatherController {
  constructor(private readonly service: WeatherService) {}

  @Get('/city')
  @HttpCode(200)
  async getCity(@Query('city') city: string): Promise<any> {
      return await this.service.getCity(city);
  }

  @Get('/average')
  @HttpCode(200)
  async getAverage(@Query('city') city: string): Promise<number> {
      return await this.service.getAverageTemperature(city);
  }
}

2024-09-05 05:15 UTC, andre5-augusto commented on src/weather/weather.controller.ts
O controlador precisa ser ajustado para refletir a nova lógica dos serviços e garantir que os endpoints estejam corretos.

import { Controller, Get, Query } from '@nestjs/common';
import { WeatherService } from './weather.service';
import { WeatherResponseData } from './weather.response.data';

@Controller('weather')
export class WeatherController {
  constructor(private readonly weatherService: WeatherService) {}

  @Get()
  async getWeather(@Query('city') city: string): Promise<WeatherResponseData> {
    return this.weatherService.getCity(city);
  }

  @Get('cities')
  async getWeatherForCities(@Query('cities') cities: string[]): Promise<WeatherResponseData[]> {
    return this.weatherService.getCities(cities);
  }

  @Get('average-temperature')
  async getAverageTemperature(@Query('city') city: string): Promise<string> {
    return this.weatherService.getMedia(city);
  }
}

2024-09-05 05:16 UTC, andre5-augusto commented on test/app.e2e-spec.ts
Os testes precisam ser mais abrangentes e cobrir os casos principais. Além disso, é importante configurar corretamente os testes E2E:

import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';
import { WeatherService } from './../src/services/weather.service';

describe('WeatherController (e2e)', () => {
  let app: INestApplication;
  const mockWeatherService = {
    getCity: jest.fn().mockResolvedValue({ city: 'São Paulo', temperature: 25 }),
    getCities: jest.fn().mockResolvedValue([{ city: 'São Paulo', temperature: 25 }]),
    getMedia: jest.fn().mockResolvedValue('25'),
  };

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
      providers: [
        {
          provide: WeatherService,
          useValue: mockWeatherService,
        },
      ],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/weather (GET)', () => {
    return request(app.getHttpServer())
      .get('/weather?city=São Paulo')
      .expect(200)
      .expect({

2024-09-05 05:21 UTC, andre5-augusto commented on src/weather/weather.response.data.ts
Vamos refatorar a classe WeatherResponseData para um DTO com validação apropriada:

import { IsNumber, IsOptional } from 'class-validator';

export class WeatherResponseDto {
  @IsNumber()
  cloud_pct: number;

  @IsNumber()
  temp: number;

  @IsNumber()
  feels_like: number;

  @IsNumber()
  humidity: number;

  @IsNumber()
  min_temp: number;

  @IsNumber()
  max_temp: number;

  @IsNumber()
  wind_speed: number;

  @IsNumber()
  wind_degrees: number;

  @IsNumber()
  sunrise: number;

  @IsNumber()
  sunset: number;
}

2024-09-05 21:53 UTC, andre5-augusto reviewed
A estrutura do projeto pode ser melhor organizada para facilitar a manutenção e a escalabilidade.

2024-09-05 21:53 UTC, andre5-augusto commented on README.md
A estrutura do projeto pode ser melhor organizada para facilitar a manutenção e a escalabilidade. Sugiro reorganizar as pastas e arquivos para refletir melhor a separação de responsabilidades:
src/
├── config/ # Configurações e variáveis de ambiente
│ └── config.module.ts
├── controllers/ # Controllers
│ ├── app.controller.ts
│ └── weather.controller.ts
├── services/ # Services
│ ├── app.service.ts
│ └── weather.service.ts
├── modules/ # Módulos
│ └── weather.module.ts
├── utils/ # Utilitários
├── middlewares/ # Middlewares
├── entities/ # Entidades
├── tests/ # Testes
│ ├── e2e/
│ │ └── app.e2e-spec.ts
│ ├── unit/
│ └── integration/
└── main.ts

Segue alterações sugeridas para um README mais claro:

Descrição
A Weather Forecast API é uma API simples que fornece informações de previsão do tempo para cidades específicas. A API retorna as temperaturas mínima, máxima e média para a cidade consultada.

Funcionalidades
Obtenção de previsão do tempo com base no nome da cidade.
Retorno de temperaturas mínima, máxima e média.

Pré-requisitos
Node.js (versão X.X.X ou superior)
npm (versão X.X.X ou superior)

Instalação
Clone o repositório: git clone https://github.com/seu-usuario/seu-repositorio.git
Navegue até o diretório do projeto:
cd weather-forecast-api
Instale as dependências: npm install

Executando o Projeto:
Para rodar o servidor em modo de desenvolvimento, execute: npm run start:dev

A API estará disponível no seguinte endereço: http://localhost:3000/?city=NomeDaCidade

Exemplo de Requisição: GET http://localhost:3000/?city=New York

Exemplo de Resposta:
"minTemp": 0,
"maxTemp": 4,
"averageTemp": 2
}

Testes
Para rodar os testes automatizados: npm run test

Melhorias Futuras

Suporte a múltiplas línguas para os dados meteorológicos.
Integração com diferentes APIs de previsão do tempo.
Implementação de cache para otimizar as respostas da API.

2024-09-05 21:53 UTC, andre5-augusto commented on src/weather/weather.controller.ts
O controlador precisa ser ajustado para refletir a nova lógica dos serviços e garantir que os endpoints estejam corretos.

import { Controller, Get, Query } from '@nestjs/common';
import { WeatherService } from './weather.service';
import { WeatherResponseData } from './weather.response.data';

@controller('weather')
export class WeatherController {
constructor(private readonly weatherService: WeatherService) {}

@get()
async getWeather(@query('city') city: string): Promise {
return this.weatherService.getCity(city);
}

@get('cities')
async getWeatherForCities(@query('cities') cities: string[]): Promise<WeatherResponseData[]> {
return this.weatherService.getCities(cities);
}

@get('average-temperature')
async getAverageTemperature(@query('city') city: string): Promise {
return this.weatherService.getMedia(city);
}
}

2024-09-05 21:53 UTC, andre5-augusto commented on src/weather/weather.response.data.ts
Para melhorar a estrutura e a validação dos dados relacionados ao clima, sugiro a criação de um DTO para a classe WeatherResponseData. A adição de um DTO pode ajudar a garantir a integridade dos dados e a validação automática, melhorando a qualidade do código e a segurança das informações:


import { IsNumber, IsInt, IsPositive, Min, Max } from 'class-validator';

export class WeatherResponseDto {
  @IsInt()
  @Min(0)
  @Max(100)
  readonly cloudPct: number;   // Percentual de nuvens, validado entre 0 e 100

  @IsNumber()
  readonly temp: number;       // Temperatura atual

  @IsNumber()
  readonly feelsLike: number;  // Sensação térmica

  @IsInt()
  @Min(0)
  @Max(100)
  readonly humidity: number;   // Umidade relativa em %

  @IsNumber()
  readonly minTemp: number;    // Temperatura mínima

  @IsNumber()
  readonly maxTemp: number;    // Temperatura máxima

  @IsNumber()
  @IsPositive()
  readonly windSpeed: number;  // Velocidade do vento, positivo

  @IsInt()
  readonly windDegrees: number; // Direção do vento em graus

  @IsInt()
  readonly sunrise: number;    // Timestamp de nascer do sol

  @IsInt()
  readonly sunset: number;     // Timestamp de pôr do sol
}

2024-09-05 21:53 UTC, andre5-augusto commented on src/weather/weather.service.ts
Hardcoding de chaves de API: As chaves de API estão hardcoded no código.
Tratamento de erros: O tratamento de erros pode ser melhorado.
Concorrência em chamadas assíncronas: A função getCities não lida corretamente com chamadas assíncronas.

Segue alterações sugeridas:

import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { WeatherResponseData } from './weather.response.data';
import { catchError, firstValueFrom } from 'rxjs';
import { AxiosError, AxiosRequestConfig } from 'axios';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class WeatherService {
private readonly apiKey: string;

constructor(
private readonly httpService: HttpService,
private readonly configService: ConfigService
) {
this.apiKey = this.configService.get('API_KEY');
}

private getHeaders(): AxiosRequestConfig['headers'] {
return {
'X-Api-Key': this.apiKey,
'Content-Type': 'application/json'
};
}

async getCity(city: string): Promise {
try {
const { data } = await firstValueFrom(
this.httpService.get(https://api.api-ninjas.com/v1/weather?city=${city}, { headers: this.getHeaders() }).pipe(
catchError((error: AxiosError) => {
console.error('Error fetching city data:', error.message);
throw new InternalServerErrorException('Failed to fetch city weather data');
})
)
);
return data;
} catch (err) {
throw new InternalServerErrorException('An unexpected error occurred', err.message);
}
}

async getCities(cities: string[]): Promise<WeatherResponseData[]> {
const weatherPromises = cities.map(city => this.getCity(city));
return Promise.all(weatherPromises);
}

async getMedia(city: string): Promise {
const { max_temp, min_temp } = await this.getCity(city);
return ${(max_temp + min_temp) / 2};
}
}

2024-09-05 21:53 UTC, andre5-augusto commented on test/app.e2e-spec.ts
Os testes precisam ser mais abrangentes e cobrir os casos principais. Além disso, é importante configurar corretamente os testes E2E:

import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';
import { WeatherService } from './../src/services/weather.service';

describe('WeatherController (e2e)', () => {
let app: INestApplication;
const mockWeatherService = {
getCity: jest.fn().mockResolvedValue({ city: 'São Paulo', temperature: 25 }),
getCities: jest.fn().mockResolvedValue([{ city: 'São Paulo', temperature: 25 }]),
getMedia: jest.fn().mockResolvedValue('25'),
};

beforeEach(async () => {
const moduleFixture: TestingModule = await Test.createTestingModule({
imports: [AppModule],
providers: [
{
provide: WeatherService,
useValue: mockWeatherService,
},
],
}).compile();

app = moduleFixture.createNestApplication();
await app.init();
});

it('/weather (GET)', () => {
return request(app.getHttpServer())
.get('/weather?city=São Paulo')
.expect(200)
.expect({

2024-10-01 14:09 UTC, DiegoTeles commented
Triste fazer o Review e nunca receber uma resposta do processo seletivo, mas fica como aprendizado né

2025-03-05 21:29 UTC, eduaugusto10 reviewed
Acredito que o que marquei foram os maiores erros, pode ser que existam outros menores, mas vamos com calma com o estagiário.

2025-03-05 21:29 UTC, eduaugusto10 commented on src/main.ts
> +async function bootstrap() {
Seria interessante ja deixar configurado o CORS, mesmo que coloque o asterisco (*) e assim no futuro deixar liberado apenas as urls configuradas.

2025-03-05 21:29 UTC, eduaugusto10 commented on src/main.ts
> +  await app.listen(3001);
Coloque a porta em uma variável de ambiente e depois importe para o arquivo, isso vai ajudar no momente de fazer o deploy e for configurar os ambientes no kuberneters, fica mais facil alterar a porta sem a necessidade de gerar uma nova versão de código.

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.controller.ts
> +  @HttpCode(201)
Para requisição get, quando o retorno vem sem erro o correto seria 200, e por ser um get correto não é utilizar body e sim inserir na url, pode ser como um queyparam.
Então voce vai alterar para @query('city') city: string...
Caso tenha outros parametros possiveis para se passar, aconselho a criar um DTO

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.controller.ts
> +  async getCities(@Body() city: string): Promise<any> {
Para requisição get, quando o retorno vem sem erro o correto seria 200, e por ser um get correto não é utilizar body e sim inserir na url, pode ser como um queyparam.
Então voce vai alterar para @query('city') city: string...
Caso tenha outros parametros possiveis para se passar, aconselho a criar um DTO

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.controller.ts
> +  @HttpCode(201)
Para requisição get, quando o retorno vem sem erro o correto seria 200, e por ser um get correto não é utilizar body e sim inserir na url, pode ser como um queyparam.
Então voce vai alterar para @query('city') city: string...
Caso tenha outros parametros possiveis para se passar, aconselho a criar um DTO

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.controller.ts
> +    const response = this.service.getCity(city);
O interessante seria pegar as duas requisições o inserir no service e lá dentro do service fazer os cálculos.
Não esqueça que precisa inserir um await para fazer qualquer requisição assincrona, senão sem o await vai retornar undefined ou quebrar a aplicação.
Não esqueça, que o calculo é melhor no service, pois esses cálculos estão dentro das regras de negócio, o service é específico para isso.

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +          'X-Api-Key': 'x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr',
Colocar a api-key como variável de ambiente, ou seja, crie um arquivo .env e insira o nome da variável com o seu valor, é de bons modos colocar no arquivo .env o nome da variavel em maiúsculo:
X_API_KEY=x7x1/ROfdQInbFu1j60j7g==qDJQLrZgbMHe5Azr

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +  async getCity(city: any): Promise<WeatherResponseData> {
Não utilize any, pois estaria diminuindo a segurança do código, por ser somente um parametro, então deixe assim:
getCity(city: string)

se fossem vários parametros seria interessante em pensar em implementar uma interface

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +  async getCities(cities: any): Promise<Array<WeatherResponseData>> {
Não utilize any, pois estaria diminuindo a segurança do código, por ser somente um parametro, então deixe assim:
getCities(cities: string)

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +  async getMedia(city: any): Promise<string> {
Não utilize any, pois estaria diminuindo a segurança do código, por ser somente um parametro, então deixe assim:
getMedia(city: string)

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +    cities.array.forEach(async element => {
o forEach não pode ser assincrono e com isso não será aguardado terminar uma requisição para iniciar outra, aconselho a utilizar o for...of que além de poder utilizar async, em comparação a velocidade ele é melhor que o foreach

2025-03-05 21:29 UTC, eduaugusto10 commented on src/weather/weather.service.ts
> +          this.httpService.get<WeatherResponseData>(`https://api.api-ninjas.com/v1/weather?city=${city.city}`, rc).pipe(
Seguindo a ideia de hexagonal, essa chamada deverá ficar dentro de um repository e nele retornar o objeto somente para a função.